// Generated by CoffeeScript 1.8.0
(function() {
  var app, should;

  should = require('chai').should();

  app = require('../../app');

  describe('blogsControllers', function() {});

}).call(this);
