// Generated by CoffeeScript 1.8.0
(function() {
  var app, db, express, http, mongoose, path;

  express = require('express');

  http = require('http');

  mongoose = require('mongoose');

  path = require('path');

  db = require('./config/db');

  app = express();

  require('./config/express')(app);

  require('./config/routes')(app);

  app.on('close', function(err) {
    return db.disconnect();
  });

  http.createServer(app).listen(app.get('port', function() {
    return console.log('soBlog is listening on port ' + app.get('port'));
  }));

  module.exports = app;

}).call(this);
